spring.application.name=testvue
spring.main.banner-mode=off
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
logging.level.com.microsoft.playwright=OFF
logging.level.org.apache.http=ERROR
logging.level.org.springframework=WARN
logging.level.root=WARN